name: CI/CD Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ martrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ martrix.node-version }}
      - run: npm run git-build
      - run: npx tsc
