name: ES-Lint

on: 
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  es-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ESlint Runner Action
        uses: tinovyatkin/action-eslint@v1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
